- name: "Add node.js from Nodesource"
  become: true
  shell: |
    get_url:
       url: https://deb.nodesource.com/setup_13.x | sudo -E bash -

    

- name: "Install Node.js 13"
  become: true
  apt: 
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present